import {
  ColorPalette,
  Texture,
  Material,
  FurnitureReference,
  ImageAsset,
  PresetBoard,
} from "@/types/mood-board"

export const COLOR_PALETTES: ColorPalette[] = [
  {
    id: "col-japandi-warm",
    name: "Japandi Warm Sand",
    hex: "#D4C5B9",
    secondaryHexes: ["#A89B8C", "#7D6E5D", "#EBE4DC"],
    finish: "matte",
    category: "Japandi",
    tags: ["warm", "neutral", "beige", "zen"],
  },
  {
    id: "col-terracotta-sun",
    name: "Tuscan Terracotta",
    hex: "#C86D51",
    secondaryHexes: ["#8F432F", "#E5A08D", "#F4E3DD"],
    finish: "matte",
    category: "Warm Earthy",
    tags: ["earthy", "terracotta", "warm", "rust"],
  },
  {
    id: "col-sage-tranquility",
    name: "Sage Tranquility",
    hex: "#94A390",
    secondaryHexes: ["#5C6B58", "#C3CFC0", "#EFF3EE"],
    finish: "satin",
    category: "Biophilic",
    tags: ["green", "sage", "calm", "nature"],
  },
  {
    id: "col-brushed-gold",
    name: "Brushed Champagne Gold",
    hex: "#D4AF37",
    secondaryHexes: ["#AA8C2C", "#F3E5AB", "#7B661B"],
    finish: "metallic",
    category: "Luxury Accents",
    tags: ["gold", "metal", "luxurious", "brass"],
  },
  {
    id: "col-charcoal-noir",
    name: "Deep Slate Noir",
    hex: "#2B2D31",
    secondaryHexes: ["#1A1C1E", "#4E5158", "#90949D"],
    finish: "matte",
    category: "Modern Minimalist",
    tags: ["dark", "charcoal", "sleek", "dramatic"],
  },
  {
    id: "col-creme-de-la-creme",
    name: "Crème Velvet",
    hex: "#F5F0EB",
    secondaryHexes: ["#E3D9CE", "#BFB2A3", "#FFFFFF"],
    finish: "matte",
    category: "Japandi",
    tags: ["ivory", "white", "soft", "clean"],
  },
  {
    id: "col-nordic-sky",
    name: "Nordic Blue Fog",
    hex: "#7B8E99",
    secondaryHexes: ["#485863", "#ADC0CB", "#E6EEF3"],
    finish: "satin",
    category: "Scandinavian",
    tags: ["blue", "coastal", "cool", "fog"],
  },
  {
    id: "col-olive-grove",
    name: "Olive Grove",
    hex: "#556B2F",
    secondaryHexes: ["#38471F", "#8CA856", "#E8EFE0"],
    finish: "matte",
    category: "Biophilic",
    tags: ["green", "olive", "forest", "earthy"],
  },
]

export const TEXTURES: Texture[] = [
  {
    id: "tex-boucle-ivory",
    name: "Ivory Bouclé Wool",
    category: "Fabrics",
    tactileDescription: "Heavy nubby loop texture with ultra-soft plush touch",
    imageUrl: "/images/portfolio-1.jpg",
    patternType: "Textured Knit",
    suggestedUse: "Upholstery, Accent Pillows, Loungers",
  },
  {
    id: "tex-linen-slub",
    name: "Belgian Natural Slub Linen",
    category: "Fabrics",
    tactileDescription: "Breathable organic weave with subtle uneven flax slubs",
    imageUrl: "/images/portfolio-2.jpg",
    patternType: "Plain Weave",
    suggestedUse: "Drapery, Bedding, Roman Shades",
  },
  {
    id: "tex-fluted-wood",
    name: "Tambour Fluted Oak Panel",
    category: "Wall Coverings",
    tactileDescription: "Rhythmic semicircular vertical wooden grooves",
    imageUrl: "/images/portfolio-3.jpg",
    patternType: "Architectural Fluting",
    suggestedUse: "Feature Walls, Kitchen Islands, Headboards",
  },
  {
    id: "tex-calacatta-vein",
    name: "Calacatta Gold Marble Grain",
    category: "Stone Surface",
    tactileDescription: "Polished cold stone with thick grey and warm honey veining",
    imageUrl: "/images/portfolio-4.jpg",
    patternType: "Organic Vein",
    suggestedUse: "Countertops, Backsplashes, Mantels",
  },
  {
    id: "tex-ribbed-glass",
    name: "Architectural Reeded Glass",
    category: "Glass & Acrylic",
    tactileDescription: "Parallel linear ridges creating diffused light reflection",
    imageUrl: "/images/portfolio-5.jpg",
    patternType: "Reeded/Fluted",
    suggestedUse: "Cabinet Doors, Partitions, Light Fixtures",
  },
  {
    id: "tex-woven-rattan",
    name: "Handwoven Caned Rattan",
    category: "Natural Fibers",
    tactileDescription: "Octagonal traditional cane webbing weave pattern",
    imageUrl: "/images/portfolio-6.jpg",
    patternType: "Geometric Weave",
    suggestedUse: "Chair Backs, Credenza Insets, Screen Panels",
  },
]

export const MATERIALS: Material[] = [
  {
    id: "mat-white-oak",
    name: "Honest European White Oak",
    category: "wood",
    finish: "Matte Natural Oil",
    imageUrl: "/images/portfolio-1.jpg",
    origin: "France",
    sustainabilityRating: "FSC Certified 100%",
  },
  {
    id: "mat-carrara-marble",
    name: "Carrara Honed Marble",
    category: "stone",
    finish: "Honed Low-Sheen",
    imageUrl: "/images/portfolio-4.jpg",
    origin: "Tuscany, Italy",
    sustainabilityRating: "Quarried Natural Stone",
  },
  {
    id: "mat-brushed-brass",
    name: "Aged Satin Brass",
    category: "metal",
    finish: "Hand-Brushed & Sealed",
    imageUrl: "/images/portfolio-3.jpg",
    origin: "UK",
    sustainabilityRating: "100% Recyclable",
  },
  {
    id: "mat-velvet-rust",
    name: "Terracotta Cotton Velvet",
    category: "fabric",
    finish: "Short Pile Soft Lustre",
    imageUrl: "/images/hero-interior.jpg",
    origin: "Belgium",
    sustainabilityRating: "Oeko-Tex Standard 100",
  },
  {
    id: "mat-cognac-leather",
    name: "Full-Grain Cognac Saddle Leather",
    category: "leather",
    finish: "Aniline Patina Wax",
    imageUrl: "/images/about-hero.jpg",
    origin: "Italy",
    sustainabilityRating: "Vegetable Tanned",
  },
  {
    id: "mat-zellige-tile",
    name: "Artisanal White Zellige Clay Tile",
    category: "ceramic",
    finish: "Hand-Glazed Gloss",
    imageUrl: "/images/portfolio-2.jpg",
    origin: "Fez, Morocco",
    sustainabilityRating: "Handmade Artisanal",
  },
]

export const FURNITURE_ITEMS: FurnitureReference[] = [
  {
    id: "fur-sofa-curved",
    name: "Solaia Organic Curved Sofa",
    category: "Seating",
    dimensions: "W 240 x D 110 x H 78 cm",
    estimatedPrice: "$3,450",
    vendor: "NestSpace Signature Studio",
    imageUrl: "/images/portfolio-1.jpg",
    style: "Japandi Modern",
  },
  {
    id: "fur-armchair-boucle",
    name: "Kumo Swivel Accent Lounge Chair",
    category: "Chairs",
    dimensions: "W 92 x D 88 x H 74 cm",
    estimatedPrice: "$1,280",
    vendor: "Kyoto Living Co.",
    imageUrl: "/images/hero-interior.jpg",
    style: "Warm Minimalist",
  },
  {
    id: "fur-coffee-plinth",
    name: "Travertine Block Coffee Table",
    category: "Tables",
    dimensions: "W 120 x D 70 x H 34 cm",
    estimatedPrice: "$1,890",
    vendor: "Atelier Stone & Wood",
    imageUrl: "/images/portfolio-4.jpg",
    style: "Contemporary Luxury",
  },
  {
    id: "fur-pendant-paper",
    name: "Wabi-Sabi Sculptural Lantern Pendant",
    category: "Lighting",
    dimensions: "Dia 75 x H 65 cm",
    estimatedPrice: "$620",
    vendor: "Noguchi Studio Edition",
    imageUrl: "/images/portfolio-5.jpg",
    style: "Organic Craft",
  },
  {
    id: "fur-credenza-walnut",
    name: "Linear Fluted Walnut Credenza",
    category: "Storage",
    dimensions: "W 180 x D 48 x H 72 cm",
    estimatedPrice: "$2,650",
    vendor: "Nordic Heritage Modern",
    imageUrl: "/images/portfolio-3.jpg",
    style: "Mid-Century Modern",
  },
  {
    id: "fur-mirror-asymmetric",
    name: "Fluid Brass Edge Wall Mirror",
    category: "Decor & Mirrors",
    dimensions: "W 85 x H 145 cm",
    estimatedPrice: "$890",
    vendor: "Milan Design Lab",
    imageUrl: "/images/portfolio-6.jpg",
    style: "Artisan Modern",
  },
]

export const INSPIRATION_IMAGES: ImageAsset[] = [
  {
    id: "img-living-japandi",
    title: "Sunlit Minimalist Living Room",
    category: "Living Rooms",
    imageUrl: "/images/portfolio-1.jpg",
    aspectRatio: "landscape",
    tags: ["japandi", "sunlight", "sofa", "arch"],
  },
  {
    id: "img-kitchen-marble",
    title: "Architectural Marble Kitchen Island",
    category: "Kitchens",
    imageUrl: "/images/portfolio-2.jpg",
    aspectRatio: "landscape",
    tags: ["kitchen", "marble", "pendant", "stools"],
  },
  {
    id: "img-study-wood",
    title: "Warm Executive Study & Bookshelf",
    category: "Offices",
    imageUrl: "/images/portfolio-3.jpg",
    aspectRatio: "portrait",
    tags: ["office", "bookshelf", "wood", "study"],
  },
  {
    id: "img-bath-spa",
    title: "Monolithic Spa Bathroom",
    category: "Bathrooms",
    imageUrl: "/images/portfolio-4.jpg",
    aspectRatio: "square",
    tags: ["bathroom", "tub", "stone", "spa"],
  },
  {
    id: "img-dining-pendant",
    title: "Sculptural Dining Nook",
    category: "Dining Rooms",
    imageUrl: "/images/portfolio-5.jpg",
    aspectRatio: "portrait",
    tags: ["dining", "table", "chandelier", "warm"],
  },
  {
    id: "img-penthouse-stair",
    title: "Double Height Skyline Lounge",
    category: "Living Rooms",
    imageUrl: "/images/portfolio-6.jpg",
    aspectRatio: "landscape",
    tags: ["luxury", "penthouse", "city", "high-ceiling"],
  },
]

export const PRESET_MOOD_BOARDS: PresetBoard[] = [
  {
    id: "preset-japandi-sanctuary",
    title: "Japandi Sanctuary Living",
    description: "Harmonious blend of Japanese wabi-sabi minimalism and Scandinavian warmth featuring tactile bouclé, natural oak, and sand tones.",
    category: "Living Room",
    coverImage: "/images/portfolio-1.jpg",
    items: [
      {
        type: "image",
        x: 40,
        y: 40,
        width: 320,
        height: 220,
        zIndex: 1,
        title: "Sunlit Minimalist Living Room",
        imageData: INSPIRATION_IMAGES[0],
        frameStyle: "shadow",
      },
      {
        type: "color",
        x: 380,
        y: 40,
        width: 220,
        height: 140,
        zIndex: 2,
        title: "Sand Color Swatch",
        colorData: COLOR_PALETTES[0],
      },
      {
        type: "texture",
        x: 380,
        y: 200,
        width: 240,
        height: 160,
        zIndex: 3,
        title: "Ivory Bouclé Wool",
        textureData: TEXTURES[0],
      },
      {
        type: "furniture",
        x: 40,
        y: 280,
        width: 320,
        height: 200,
        zIndex: 4,
        title: "Organic Curved Sofa",
        furnitureData: FURNITURE_ITEMS[0],
      },
      {
        type: "note",
        x: 640,
        y: 40,
        width: 220,
        height: 150,
        zIndex: 5,
        title: "Design Concept Note",
        noteData: {
          text: "Focus on tactile textures, soft curved silhouettes, low-profile furniture, and layered warm natural light.",
          backgroundColor: "rgba(245, 240, 235, 0.95)",
          textColor: "#2B2D31",
          fontSize: "base",
        },
      },
    ],
  },
  {
    id: "preset-warm-luxury",
    title: "Warm Modern Luxury Suite",
    description: "Rich Italian marble, cognac full-grain leather, brushed champagne gold accents, and deep charcoal contours.",
    category: "Primary Suite",
    coverImage: "/images/portfolio-4.jpg",
    items: [
      {
        type: "image",
        x: 40,
        y: 40,
        width: 340,
        height: 240,
        zIndex: 1,
        title: "Monolithic Spa Bathroom",
        imageData: INSPIRATION_IMAGES[3],
        frameStyle: "rounded",
      },
      {
        type: "material",
        x: 400,
        y: 40,
        width: 240,
        height: 180,
        zIndex: 2,
        title: "Carrara Honed Marble",
        materialData: MATERIALS[1],
      },
      {
        type: "color",
        x: 660,
        y: 40,
        width: 200,
        height: 150,
        zIndex: 3,
        title: "Brushed Champagne Gold",
        colorData: COLOR_PALETTES[3],
      },
      {
        type: "furniture",
        x: 400,
        y: 240,
        width: 300,
        height: 190,
        zIndex: 4,
        title: "Travertine Coffee Table",
        furnitureData: FURNITURE_ITEMS[2],
      },
    ],
  },
  {
    id: "preset-biophilic-executive",
    title: "Biophilic Executive Workspace",
    description: "Calming sage greens, tambour fluted wall panels, ergonomic statement seating, and natural indoor flora.",
    category: "Office",
    coverImage: "/images/portfolio-3.jpg",
    items: [
      {
        type: "image",
        x: 40,
        y: 40,
        width: 300,
        height: 260,
        zIndex: 1,
        title: "Warm Executive Study",
        imageData: INSPIRATION_IMAGES[2],
        frameStyle: "polaroid",
      },
      {
        type: "color",
        x: 360,
        y: 40,
        width: 220,
        height: 140,
        zIndex: 2,
        title: "Sage Tranquility",
        colorData: COLOR_PALETTES[2],
      },
      {
        type: "texture",
        x: 600,
        y: 40,
        width: 240,
        height: 160,
        zIndex: 3,
        title: "Fluted Wood Panel",
        textureData: TEXTURES[2],
      },
    ],
  },
]
