import { FurnitureTemplate, RoomPreset, RoomType } from "@/types/room-planner"

export const FURNITURE_TEMPLATES: FurnitureTemplate[] = [
  // Living Room
  {
    id: "sofa-l-shape",
    name: "Sectional L-Sofa",
    category: "living-room",
    width: 160,
    height: 120,
    iconName: "Sofa",
    defaultRotation: 0,
    color: "#b45309", // Warm bronze amber
    description: "Modern L-shaped 5-seater sectional sofa",
    minWidth: 120,
    maxWidth: 220,
    minHeight: 100,
    maxHeight: 180,
  },
  {
    id: "sofa-3-seater",
    name: "3-Seater Couch",
    category: "living-room",
    width: 140,
    height: 70,
    iconName: "Sofa",
    defaultRotation: 0,
    color: "#d97706",
    description: "Plush velvet 3-seater living room couch",
    minWidth: 100,
    maxWidth: 180,
    minHeight: 50,
    maxHeight: 100,
  },
  {
    id: "armchair-lounge",
    name: "Accent Armchair",
    category: "living-room",
    width: 70,
    height: 70,
    iconName: "Armchair",
    defaultRotation: 0,
    color: "#ca8a04",
    description: "Ergonomic leather swivel accent chair",
    minWidth: 50,
    maxWidth: 100,
    minHeight: 50,
    maxHeight: 100,
  },
  {
    id: "coffee-table-marble",
    name: "Coffee Table",
    category: "living-room",
    width: 90,
    height: 50,
    iconName: "Table",
    defaultRotation: 0,
    color: "#78716c",
    description: "Oval marble top center coffee table",
    minWidth: 60,
    maxWidth: 140,
    minHeight: 40,
    maxHeight: 80,
  },
  {
    id: "tv-unit-console",
    name: "Media TV Console",
    category: "living-room",
    width: 150,
    height: 40,
    iconName: "Tv",
    defaultRotation: 0,
    color: "#44403c",
    description: "Floating wood TV media console unit",
    minWidth: 100,
    maxWidth: 200,
    minHeight: 30,
    maxHeight: 60,
  },

  // Bedroom
  {
    id: "bed-king",
    name: "King Bed & Headboard",
    category: "bedroom",
    width: 150,
    height: 160,
    iconName: "BedDouble",
    defaultRotation: 0,
    color: "#4f46e5",
    description: "Luxury upholstered king bed with integrated headboard",
    minWidth: 120,
    maxWidth: 180,
    minHeight: 140,
    maxHeight: 200,
  },
  {
    id: "bed-queen",
    name: "Queen Bed",
    category: "bedroom",
    width: 130,
    height: 140,
    iconName: "Bed",
    defaultRotation: 0,
    color: "#6366f1",
    description: "Minimalist timber queen size platform bed",
    minWidth: 100,
    maxWidth: 160,
    minHeight: 120,
    maxHeight: 180,
  },
  {
    id: "nightstand-wood",
    name: "Bedside Nightstand",
    category: "bedroom",
    width: 45,
    height: 45,
    iconName: "Box",
    defaultRotation: 0,
    color: "#818cf8",
    description: "Dual-drawer wooden bedside table",
    minWidth: 35,
    maxWidth: 60,
    minHeight: 35,
    maxHeight: 60,
  },
  {
    id: "wardrobe-large",
    name: "Full Wardrobe Closet",
    category: "bedroom",
    width: 160,
    height: 60,
    iconName: "DoorClosed",
    defaultRotation: 0,
    color: "#3730a3",
    description: "3-door fitted wooden wardrobe with mirror panel",
    minWidth: 100,
    maxWidth: 220,
    minHeight: 45,
    maxHeight: 80,
  },

  // Kitchen & Dining
  {
    id: "dining-table-6",
    name: "6-Seater Dining Table",
    category: "kitchen",
    width: 160,
    height: 90,
    iconName: "Utensils",
    defaultRotation: 0,
    color: "#059669",
    description: "Solid oak dining table for family dinners",
    minWidth: 120,
    maxWidth: 200,
    minHeight: 70,
    maxHeight: 110,
  },
  {
    id: "dining-table-round",
    name: "Round Dining Table",
    category: "kitchen",
    width: 100,
    height: 100,
    iconName: "CircleDot",
    defaultRotation: 0,
    color: "#10b981",
    description: "4-seater round pedestal dining table",
    minWidth: 80,
    maxWidth: 140,
    minHeight: 80,
    maxHeight: 140,
  },
  {
    id: "kitchen-island",
    name: "Kitchen Island Bar",
    category: "kitchen",
    width: 180,
    height: 80,
    iconName: "Columns3",
    defaultRotation: 0,
    color: "#047857",
    description: "Marble waterfall kitchen island with breakfast bar",
    minWidth: 140,
    maxWidth: 240,
    minHeight: 60,
    maxHeight: 100,
  },

  // Office
  {
    id: "office-desk-exec",
    name: "Executive Desk",
    category: "office",
    width: 140,
    height: 70,
    iconName: "Laptop",
    defaultRotation: 0,
    color: "#0284c7",
    description: "Ergonomic executive workspace desk with cable routing",
    minWidth: 100,
    maxWidth: 180,
    minHeight: 50,
    maxHeight: 90,
  },
  {
    id: "office-chair",
    name: "Ergonomic Chair",
    category: "office",
    width: 55,
    height: 55,
    iconName: "Armchair",
    defaultRotation: 0,
    color: "#0369a1",
    description: "High-back mesh ergonomic office chair",
    minWidth: 45,
    maxWidth: 70,
    minHeight: 45,
    maxHeight: 70,
  },
  {
    id: "bookshelf-tall",
    name: "Tall Bookcase",
    category: "office",
    width: 100,
    height: 40,
    iconName: "Library",
    defaultRotation: 0,
    color: "#075985",
    description: "5-tier vertical shelving bookcase",
    minWidth: 70,
    maxWidth: 150,
    minHeight: 30,
    maxHeight: 60,
  },

  // Decor & Accents
  {
    id: "decor-plant-monstera",
    name: "Indoor Plant",
    category: "decor",
    width: 45,
    height: 45,
    iconName: "Flower2",
    defaultRotation: 0,
    color: "#16a34a",
    description: "Potted Monstera indoor ceramic planter",
    minWidth: 30,
    maxWidth: 70,
    minHeight: 30,
    maxHeight: 70,
  },
  {
    id: "decor-rug-large",
    name: "Area Accent Rug",
    category: "decor",
    width: 180,
    height: 120,
    iconName: "Grid",
    defaultRotation: 0,
    color: "#a8a29e",
    description: "Soft plush geometric woven area rug",
    minWidth: 120,
    maxWidth: 260,
    minHeight: 80,
    maxHeight: 180,
  },
  {
    id: "decor-floor-lamp",
    name: "Arched Floor Lamp",
    category: "decor",
    width: 40,
    height: 40,
    iconName: "Lamp",
    defaultRotation: 0,
    color: "#eab308",
    description: "Brass arched contemporary standing floor lamp",
    minWidth: 30,
    maxWidth: 60,
    minHeight: 30,
    maxHeight: 60,
  },
]

export const ROOM_PRESETS: Record<RoomType, RoomPreset> = {
  "living-room": {
    type: "living-room",
    label: "Living Room",
    width: 720,
    height: 480,
    gridSize: 20,
    description: "Spacious layout optimized for sofas, entertainment consoles, and lounge seating.",
    defaultItems: [
      {
        templateId: "sofa-l-shape",
        name: "Sectional L-Sofa",
        category: "living-room",
        x: 100,
        y: 120,
        width: 160,
        height: 120,
        rotation: 0,
        color: "#b45309",
        iconName: "Sofa",
      },
      {
        templateId: "coffee-table-marble",
        name: "Coffee Table",
        category: "living-room",
        x: 300,
        y: 160,
        width: 90,
        height: 50,
        rotation: 0,
        color: "#78716c",
        iconName: "Table",
      },
      {
        templateId: "tv-unit-console",
        name: "Media TV Console",
        category: "living-room",
        x: 260,
        y: 40,
        width: 160,
        height: 40,
        rotation: 0,
        color: "#44403c",
        iconName: "Tv",
      },
      {
        templateId: "decor-plant-monstera",
        name: "Indoor Plant",
        category: "decor",
        x: 460,
        y: 40,
        width: 45,
        height: 45,
        rotation: 0,
        color: "#16a34a",
        iconName: "Flower2",
      },
    ],
  },
  bedroom: {
    type: "bedroom",
    label: "Master Bedroom",
    width: 660,
    height: 440,
    gridSize: 20,
    description: "Peaceful floor plan designed for beds, nightstands, and wardrobes.",
    defaultItems: [
      {
        templateId: "bed-king",
        name: "King Bed & Headboard",
        category: "bedroom",
        x: 240,
        y: 60,
        width: 150,
        height: 160,
        rotation: 0,
        color: "#4f46e5",
        iconName: "BedDouble",
      },
      {
        templateId: "nightstand-wood",
        name: "Bedside Nightstand",
        category: "bedroom",
        x: 180,
        y: 60,
        width: 45,
        height: 45,
        rotation: 0,
        color: "#818cf8",
        iconName: "Box",
      },
      {
        templateId: "nightstand-wood",
        name: "Bedside Nightstand",
        category: "bedroom",
        x: 405,
        y: 60,
        width: 45,
        height: 45,
        rotation: 0,
        color: "#818cf8",
        iconName: "Box",
      },
      {
        templateId: "wardrobe-large",
        name: "Full Wardrobe Closet",
        category: "bedroom",
        x: 60,
        y: 280,
        width: 160,
        height: 60,
        rotation: 0,
        color: "#3730a3",
        iconName: "DoorClosed",
      },
    ],
  },
  kitchen: {
    type: "kitchen",
    label: "Kitchen & Dining",
    width: 640,
    height: 440,
    gridSize: 20,
    description: "Culinary space arrangement featuring islands, counters, and dining setups.",
    defaultItems: [
      {
        templateId: "kitchen-island",
        name: "Kitchen Island Bar",
        category: "kitchen",
        x: 120,
        y: 80,
        width: 180,
        height: 80,
        rotation: 0,
        color: "#047857",
        iconName: "Columns3",
      },
      {
        templateId: "dining-table-6",
        name: "6-Seater Dining Table",
        category: "kitchen",
        x: 360,
        y: 180,
        width: 160,
        height: 90,
        rotation: 0,
        color: "#059669",
        iconName: "Utensils",
      },
    ],
  },
  office: {
    type: "office",
    label: "Executive Office",
    width: 600,
    height: 420,
    gridSize: 20,
    description: "Productivity layout for executive desks, ergonomic chairs, and bookcases.",
    defaultItems: [
      {
        templateId: "office-desk-exec",
        name: "Executive Desk",
        category: "office",
        x: 200,
        y: 100,
        width: 140,
        height: 70,
        rotation: 0,
        color: "#0284c7",
        iconName: "Laptop",
      },
      {
        templateId: "office-chair",
        name: "Ergonomic Chair",
        category: "office",
        x: 240,
        y: 185,
        width: 55,
        height: 55,
        rotation: 0,
        color: "#0369a1",
        iconName: "Armchair",
      },
      {
        templateId: "bookshelf-tall",
        name: "Tall Bookcase",
        category: "office",
        x: 40,
        y: 40,
        width: 100,
        height: 40,
        rotation: 0,
        color: "#075985",
        iconName: "Library",
      },
    ],
  },
  apartment: {
    type: "apartment",
    label: "Studio Apartment",
    width: 760,
    height: 500,
    gridSize: 20,
    description: "Multi-zonal compact plan combining sleeping, lounging, and dining areas.",
    defaultItems: [
      {
        templateId: "bed-queen",
        name: "Queen Bed",
        category: "bedroom",
        x: 60,
        y: 60,
        width: 130,
        height: 140,
        rotation: 0,
        color: "#6366f1",
        iconName: "Bed",
      },
      {
        templateId: "sofa-3-seater",
        name: "3-Seater Couch",
        category: "living-room",
        x: 360,
        y: 100,
        width: 140,
        height: 70,
        rotation: 0,
        color: "#d97706",
        iconName: "Sofa",
      },
      {
        templateId: "dining-table-round",
        name: "Round Dining Table",
        category: "kitchen",
        x: 520,
        y: 280,
        width: 100,
        height: 100,
        rotation: 0,
        color: "#10b981",
        iconName: "CircleDot",
      },
    ],
  },
}

export const MATCHING_DESIGNS: Record<
  RoomType,
  {
    title: string
    category: string
    image: string
    location: string
    description: string
    portfolioSlug: string
  }[]
> = {
  "living-room": [
    {
      title: "Modern Living Room",
      category: "Home",
      image: "/images/portfolio-1.jpg",
      location: "Manhattan, NY",
      description: "Clean lines and open space layout with warm neutral tones.",
      portfolioSlug: "modern-living-room",
    },
    {
      title: "Penthouse Living",
      category: "Luxury",
      image: "/images/portfolio-6.jpg",
      location: "New York, NY",
      description: "Double-height ceilings and custom spiral staircase skyline lounge.",
      portfolioSlug: "penthouse-living",
    },
  ],
  bedroom: [
    {
      title: "Cozy Bedroom",
      category: "Home",
      image: "/images/hero-interior.jpg",
      location: "Seattle, WA",
      description: "Serene bedroom retreat with warm textures and soft accent lighting.",
      portfolioSlug: "cozy-bedroom",
    },
    {
      title: "Spa Bathroom Suite",
      category: "Luxury",
      image: "/images/portfolio-4.jpg",
      location: "Miami, FL",
      description: "Resort-style luxury primary suite retreat.",
      portfolioSlug: "spa-bathroom",
    },
  ],
  kitchen: [
    {
      title: "Luxury Kitchen",
      category: "Kitchen",
      image: "/images/portfolio-2.jpg",
      location: "Beverly Hills, CA",
      description: "Premium materials, quartz waterfall island, and professional appliances.",
      portfolioSlug: "luxury-kitchen",
    },
    {
      title: "Elegant Dining",
      category: "Home",
      image: "/images/portfolio-5.jpg",
      location: "San Francisco, CA",
      description: "Formal dining space with statement lighting and extendable table.",
      portfolioSlug: "elegant-dining",
    },
  ],
  office: [
    {
      title: "Executive Office",
      category: "Office",
      image: "/images/portfolio-3.jpg",
      location: "Chicago, IL",
      description: "Refined study workspace balancing commanding presence and flexibility.",
      portfolioSlug: "executive-office",
    },
    {
      title: "Modern Workspace",
      category: "Office",
      image: "/images/about-hero.jpg",
      location: "Austin, TX",
      description: "Collaborative studio with acoustic privacy and ergonomic workstations.",
      portfolioSlug: "modern-workspace",
    },
  ],
  apartment: [
    {
      title: "Modern Living Room",
      category: "Home",
      image: "/images/portfolio-1.jpg",
      location: "Manhattan, NY",
      description: "Optimized urban open floor concept.",
      portfolioSlug: "modern-living-room",
    },
    {
      title: "Penthouse Living",
      category: "Luxury",
      image: "/images/portfolio-6.jpg",
      location: "New York, NY",
      description: "Luxury spatial zoning for compact high-rise living.",
      portfolioSlug: "penthouse-living",
    },
  ],
}
